# .readthedocs.yaml
# Read the Dcos configuration file

version: 2

build:
  os: ubuntu-22.04
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml