# .readthedocs.yml
# Read the Dcos configuration file

version: 2

python:
  version: 3.7
  install:
    - method: pip
      path: .
      requirements: docs/requirements.txt    

mkdocs:
  configuration: mkdocs.yml